name: geolocator_web
description: Official web implementation of the geolocator plugin.
repository: https://github.com/Baseflow/flutter-geolocator/tree/geolocator_web
issue_tracker: https://github.com/Baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 2.0.7

flutter:
  plugin:
    platforms:
      web:
        pluginClass: GeolocatorPlugin
        fileName: geolocator_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  geolocator_platform_interface: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mockito: ^5.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"
