name: geolocator_apple
description: Geolocation Apple plugin for Flutter. This plugin provides the Apple implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_apple
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 2.2.5

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: geolocator
    platforms:
      ios:
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorApple
      macos:
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorApple

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface: ^4.0.5

dev_dependencies:
  async: ^2.8.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2
