name: geolocator_example
description: Demonstrates how to use the geolocator plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  baseflow_plugin_template:
    git:
      url: git://github.com/Baseflow/baseflow_plugin_template.git
      ref: v1.0.0
  flutter:
    sdk: flutter

  geolocator:
    # When depending on this package from a real application you should use:
    #   geolocator: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # The following adds the URL Launcher plugin which is used by
  # the demo application to open the links in the web browser.
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - res/images/baseflow_logo_def_light-02.png
    - res/images/poweredByBaseflowLogoLight@3x.png
    - packages/baseflow_plugin_template/logo.png
    - packages/baseflow_plugin_template/poweredByBaseflow.png