name: geolocator_platform_interface
description: A common platform interface for the geolocator plugin.
homepage: https://github.com/baseflow/flutter-geolocator
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0

dependencies:
  flutter:
    sdk: flutter
  
  plugin_platform_interface: ^2.0.0
  vector_math: ^2.1.0
  meta: ^1.3.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
  mockito: ^5.0.0-nullsafety.7

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.10.0"
