name: geolocator_platform_interface
description: A common platform interface for the geolocator plugin.
homepage: https://github.com/baseflow/flutter-geolocator/tree/master/geolocator_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.1.8
  plugin_platform_interface: ^1.0.2
  vector_math: ^2.0.8

dev_dependencies:
  async: ^2.4.2
  fake_async: ^1.1.0
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.2
  mockito: ^4.1.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"
