name: geolocator_platform_interface
description: A common platform interface for the geolocator plugin.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.0.6

dependencies:
  flutter:
    sdk: flutter
  
  plugin_platform_interface: ^2.1.1
  vector_math: ^2.1.0
  meta: ^1.3.0

dev_dependencies:
  async: ^2.8.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mockito: ^5.0.0-nullsafety.7

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"
