name: geolocator_platform_interface
description: A common platform interface for the geolocator plugin.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.2.0

dependencies:
  flutter:
    sdk: flutter
  
  plugin_platform_interface: ^2.1.6
  vector_math: ^2.1.4
  meta: ^1.9.1

dev_dependencies:
  async: ^2.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.3 <4.0.0"
  mockito: ^5.4.2

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"
