name: geolocator
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
version: 7.4.0
repository: https://github.com/Baseflow/flutter-geolocator/tree/master/geolocator
issue_tracker: https://github.com/Baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android
      ios:
        default_package: geolocator_apple
      web:
        default_package: geolocator_web

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface:
    git:
      url: git://github.com/juanmanjarres/flutter-geolocator.git
      path: geolocator_platform_interface
  geolocator_web:
    git:
      url: git://github.com/juanmanjarres/flutter-geolocator.git
      path: geolocator_web
  geolocator_android: ^1.0.0
  geolocator_apple: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.0.0
