name: geolocator
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
version: 6.0.0+2
homepage: https://github.com/baseflow/flutter-geolocator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  geolocator_platform_interface: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.2
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.baseflow.geolocator
        pluginClass: GeolocatorPlugin
      ios:
        pluginClass: GeolocatorPlugin
