name: geolocator_windows
description: Geolocation Windows plugin for Flutter. This plugin provides the Windows implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_windows
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 0.1.2

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: geolocator
    platforms:
      windows:
        pluginClass: GeolocatorWindows

dependencies:
  flutter:
    sdk: flutter

  geolocator_platform_interface: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mockito: ^5.0.17
  plugin_platform_interface: ^2.1.2
