name: geolocator_android
description: Geolocation plugin for Flutter. This plugin provides the Android implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_android
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 4.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.geolocator
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorAndroid

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface: ^4.0.4

dev_dependencies:
  async: ^2.8.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2
