name: geolocator_android
description: Geolocation plugin for Flutter. This plugin provides the Android implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_android
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 4.6.2

environment:
  sdk: ^3.5.0
  flutter: ">=2.17.0"

flutter:
  plugin:
    implements: geolocator
    platforms:
      android:
        package: com.baseflow.geolocator
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorAndroid

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface: ^4.1.0
  meta: ^1.10.0
  uuid: ">=4.0.0 <6.0.0"

dev_dependencies:
  async: ^2.8.2
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0 <5.0.0"
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2
