name: geolocator_linux
description: Geolocation Linux plugin for Flutter. This plugin provides the
  Linux implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_linux
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 0.1.3

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: geolocator
    platforms:
      linux:
        dartPluginClass: GeolocatorLinux

dependencies:
  dbus: ^0.7.3
  flutter:
    sdk: flutter
  geoclue: ^0.1.1
  geolocator_platform_interface: ^4.0.0
  gsettings: ^0.2.5
  package_info_plus: ">=1.4.2 <5.0.0"

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  plugin_platform_interface: ^2.1.2
