# This is a basic workflow to help you get started with Actions

name: Geolocator

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job configuration for the geolocator_platform_interface (Platform Interface Package)
  geolocator_platform_interface:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      source-directory: ./geolocator_platform_interface 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Download all Flutter packages the geolocator depends on
      - name: Download dependencies
        run: flutter pub get
        working-directory: ${{env.source-directory}}
      
      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: flutter analyze
        working-directory: ${{env.source-directory}}
      
      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: flutter test --coverage
        working-directory: ${{env.source-directory}}

      # Upload code coverage information
      - uses: codecov/codecov-action@v1
        with:
        file: ./coverage/lcov.info # optional
        name: Geolocator (Platform Interface Package) # optional
        fail_ci_if_error: true 
        working-directory: ${{env.source-directory}}

  # Job configuration for the geolocator (App Facing Package)
  geolocator:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      source-directory: ./geolocator 
      example-directory: ./geolocator/example

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Download all Flutter packages the geolocator depends on
      - name: Download dependencies
        run: flutter pub get
        working-directory: ${{env.source-directory}}
      
      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: flutter analyze
        working-directory: ${{env.source-directory}}
      
      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: flutter test --coverage
        working-directory: ${{env.source-directory}}
      
      # Build Android version of the example app
      - name: Run Android build
        run: flutter build apk --release
        working-directory: ${{env.example-directory}}
   
      # Build iOS version of the example app
      - name: Run iOS build
        run: flutter build ios --release --no-codesign
        working-directory: ${{env.example-directory}}

      # Upload code coverage information
      - uses: codecov/codecov-action@v1
        with:
        file: ./coverage/lcov.info # optional
        name: Geolocator (App Facing Package) # optional
        fail_ci_if_error: true 
        working-directory: ${{env.source-directory}}
