name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  issues: write

jobs:
  noResponse:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'baseflow/flutter-geolocator' }}
    steps:
      - uses: godofredoc/no-response@0ce2dc0e63e1c7d2b87752ceed091f6d32c9df09
        with:
          token: ${{ github.token }}
          # Comment to post when closing an Issue for lack of response. Set to `false` to disable
          closeComment: >
            Without additional information, we are unfortunately not able to resolve this issue. 
            Therefore, we reluctantly closed this issue for now. 
            If you run into this issue later feel free to file a new issue with a reference to this issue. 
            Add a description of detailed steps to reproduce, expected and current behaviour, logs and the output of 'flutter doctor -v'. 
            Thanks for your contribution.
          # Number of days of inactivity before an issue is closed for lack of response.
          daysUntilClose: 14
          # Label requiring a response.
          responseRequiredLabel: "status: needs more info"